# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(1000, 650)
        LoginWindow.setStyleSheet("QWidget#LoginWindow {\n"
"    background-color: #1a1d3d;\n"
"}")
        self.horizontalLayout_main = QtWidgets.QHBoxLayout(LoginWindow)
        self.horizontalLayout_main.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_main.setSpacing(0)
        self.horizontalLayout_main.setObjectName("horizontalLayout_main")
        self.left_panel = QtWidgets.QFrame(LoginWindow)
        self.left_panel.setMinimumSize(QtCore.QSize(450, 0))
        self.left_panel.setMaximumSize(QtCore.QSize(450, 16777215))
        self.left_panel.setStyleSheet("QFrame#left_panel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"        stop:0 #4158D0, stop:0.5 #5B6DC9, stop:1 #C850C0);\n"
"}")
        self.left_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_panel.setObjectName("left_panel")
        self.verticalLayout_left = QtWidgets.QVBoxLayout(self.left_panel)
        self.verticalLayout_left.setObjectName("verticalLayout_left")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_left.addItem(spacerItem)
        self.title = QtWidgets.QLabel(self.left_panel)
        self.title.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"    padding: 20px;\n"
"}")
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_left.addWidget(self.title)
        self.logo_label = QtWidgets.QLabel(self.left_panel)
        self.logo_label.setStyleSheet("QLabel {\n"
"    font-size: 120px;\n"
"    padding: 30px;\n"
"}")
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.verticalLayout_left.addWidget(self.logo_label)
        self.subtitle = QtWidgets.QLabel(self.left_panel)
        self.subtitle.setStyleSheet("QLabel {\n"
"    color: rgba(255, 255, 255, 0.9);\n"
"    font-size: 20px;\n"
"    padding: 10px;\n"
"}")
        self.subtitle.setAlignment(QtCore.Qt.AlignCenter)
        self.subtitle.setObjectName("subtitle")
        self.verticalLayout_left.addWidget(self.subtitle)
        self.description = QtWidgets.QLabel(self.left_panel)
        self.description.setStyleSheet("QLabel {\n"
"    color: rgba(255, 255, 255, 0.7);\n"
"    font-size: 14px;\n"
"    padding: 20px;\n"
"}")
        self.description.setAlignment(QtCore.Qt.AlignCenter)
        self.description.setObjectName("description")
        self.verticalLayout_left.addWidget(self.description)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_left.addItem(spacerItem1)
        self.horizontalLayout_main.addWidget(self.left_panel)
        self.right_panel = QtWidgets.QFrame(LoginWindow)
        self.right_panel.setStyleSheet("QFrame#right_panel {\n"
"    background-color: #1a1d3d;\n"
"}")
        self.right_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_panel.setObjectName("right_panel")
        self.verticalLayout_right = QtWidgets.QVBoxLayout(self.right_panel)
        self.verticalLayout_right.setContentsMargins(60, 40, 60, 40)
        self.verticalLayout_right.setObjectName("verticalLayout_right")
        self.horizontalLayout_close = QtWidgets.QHBoxLayout()
        self.horizontalLayout_close.setObjectName("horizontalLayout_close")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_close.addItem(spacerItem2)
        self.btn_close = QtWidgets.QPushButton(self.right_panel)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    font-size: 32px;\n"
"    border: none;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    color: white;\n"
"}")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_close.addWidget(self.btn_close)
        self.verticalLayout_right.addLayout(self.horizontalLayout_close)
        self.login_title = QtWidgets.QLabel(self.right_panel)
        self.login_title.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-size: 28px;\n"
"    font-weight: bold;\n"
"    padding: 30px 0;\n"
"}")
        self.login_title.setAlignment(QtCore.Qt.AlignCenter)
        self.login_title.setObjectName("login_title")
        self.verticalLayout_right.addWidget(self.login_title)
        self.label_username = QtWidgets.QLabel(self.right_panel)
        self.label_username.setStyleSheet("color: white; font-size: 14px; padding: 10px 0 5px 0;")
        self.label_username.setObjectName("label_username")
        self.verticalLayout_right.addWidget(self.label_username)
        self.horizontalLayout_username = QtWidgets.QHBoxLayout()
        self.horizontalLayout_username.setSpacing(0)
        self.horizontalLayout_username.setObjectName("horizontalLayout_username")
        self.icon_username = QtWidgets.QLabel(self.right_panel)
        self.icon_username.setMinimumSize(QtCore.QSize(50, 50))
        self.icon_username.setMaximumSize(QtCore.QSize(50, 50))
        self.icon_username.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border: 2px solid rgba(255, 255, 255, 0.1);\n"
"    border-right: none;\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    font-size: 20px;\n"
"    padding: 0px;\n"
"}")
        self.icon_username.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_username.setObjectName("icon_username")
        self.horizontalLayout_username.addWidget(self.icon_username)
        self.username_input = QtWidgets.QLineEdit(self.right_panel)
        self.username_input.setMinimumSize(QtCore.QSize(0, 50))
        self.username_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border: 2px solid rgba(255, 255, 255, 0.1);\n"
"    border-left: none;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 12px 15px;\n"
"}")
        self.username_input.setObjectName("username_input")
        self.horizontalLayout_username.addWidget(self.username_input)
        self.verticalLayout_right.addLayout(self.horizontalLayout_username)
        self.label_password = QtWidgets.QLabel(self.right_panel)
        self.label_password.setStyleSheet("color: white; font-size: 14px; padding: 10px 0 5px 0;")
        self.label_password.setObjectName("label_password")
        self.verticalLayout_right.addWidget(self.label_password)
        self.horizontalLayout_password = QtWidgets.QHBoxLayout()
        self.horizontalLayout_password.setSpacing(0)
        self.horizontalLayout_password.setObjectName("horizontalLayout_password")
        self.icon_password = QtWidgets.QLabel(self.right_panel)
        self.icon_password.setMinimumSize(QtCore.QSize(50, 50))
        self.icon_password.setMaximumSize(QtCore.QSize(50, 50))
        self.icon_password.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border: 2px solid rgba(255, 255, 255, 0.1);\n"
"    border-right: none;\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    font-size: 20px;\n"
"    padding: 0px;\n"
"}")
        self.icon_password.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_password.setObjectName("icon_password")
        self.horizontalLayout_password.addWidget(self.icon_password)
        self.password_input = QtWidgets.QLineEdit(self.right_panel)
        self.password_input.setMinimumSize(QtCore.QSize(0, 50))
        self.password_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border: 2px solid rgba(255, 255, 255, 0.1);\n"
"    border-left: none;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 12px 15px;\n"
"}")
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.horizontalLayout_password.addWidget(self.password_input)
        self.verticalLayout_right.addLayout(self.horizontalLayout_password)
        self.label_captcha = QtWidgets.QLabel(self.right_panel)
        self.label_captcha.setStyleSheet("color: white; font-size: 14px; padding: 10px 0 5px 0;")
        self.label_captcha.setObjectName("label_captcha")
        self.verticalLayout_right.addWidget(self.label_captcha)
        self.horizontalLayout_captcha = QtWidgets.QHBoxLayout()
        self.horizontalLayout_captcha.setSpacing(10)
        self.horizontalLayout_captcha.setObjectName("horizontalLayout_captcha")
        self.horizontalLayout_captcha_input = QtWidgets.QHBoxLayout()
        self.horizontalLayout_captcha_input.setSpacing(0)
        self.horizontalLayout_captcha_input.setObjectName("horizontalLayout_captcha_input")
        self.icon_captcha = QtWidgets.QLabel(self.right_panel)
        self.icon_captcha.setMinimumSize(QtCore.QSize(50, 50))
        self.icon_captcha.setMaximumSize(QtCore.QSize(50, 50))
        self.icon_captcha.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border: 2px solid rgba(255, 255, 255, 0.1);\n"
"    border-right: none;\n"
"    border-top-left-radius: 12px;\n"
"    border-bottom-left-radius: 12px;\n"
"    color: rgba(255, 255, 255, 0.6);\n"
"    font-size: 20px;\n"
"    padding: 0px;\n"
"}")
        self.icon_captcha.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_captcha.setObjectName("icon_captcha")
        self.horizontalLayout_captcha_input.addWidget(self.icon_captcha)
        self.captcha_input = QtWidgets.QLineEdit(self.right_panel)
        self.captcha_input.setMinimumSize(QtCore.QSize(0, 50))
        self.captcha_input.setStyleSheet("QLineEdit {\n"
"    background-color: rgba(255, 255, 255, 0.05);\n"
"    border: 2px solid rgba(255, 255, 255, 0.1);\n"
"    border-left: none;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-right-radius: 12px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-left-radius: 0px;\n"
"    color: white;\n"
"    font-size: 14px;\n"
"    padding: 12px 15px;\n"
"}")
        self.captcha_input.setObjectName("captcha_input")
        self.horizontalLayout_captcha_input.addWidget(self.captcha_input)
        self.horizontalLayout_captcha.addLayout(self.horizontalLayout_captcha_input)
        self.captcha_display = QtWidgets.QLabel(self.right_panel)
        self.captcha_display.setMinimumSize(QtCore.QSize(100, 50))
        self.captcha_display.setMaximumSize(QtCore.QSize(100, 50))
        self.captcha_display.setStyleSheet("QLabel {\n"
"    background-color: rgba(255, 255, 255, 0.1);\n"
"    color: white;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    border: 2px solid rgba(255, 255, 255, 0.2);\n"
"    border-radius: 10px;\n"
"}")
        self.captcha_display.setAlignment(QtCore.Qt.AlignCenter)
        self.captcha_display.setObjectName("captcha_display")
        self.horizontalLayout_captcha.addWidget(self.captcha_display)
        self.refresh_btn = QtWidgets.QPushButton(self.right_panel)
        self.refresh_btn.setMinimumSize(QtCore.QSize(50, 50))
        self.refresh_btn.setMaximumSize(QtCore.QSize(50, 50))
        self.refresh_btn.setStyleSheet("QPushButton {\n"
"    background-color: #10b981;\n"
"    color: white;\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #059669;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #047857;\n"
"}")
        self.refresh_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/refrash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refresh_btn.setIcon(icon)
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout_captcha.addWidget(self.refresh_btn)
        self.verticalLayout_right.addLayout(self.horizontalLayout_captcha)
        self.login_btn = QtWidgets.QPushButton(self.right_panel)
        self.login_btn.setMinimumSize(QtCore.QSize(0, 65))
        self.login_btn.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #667eea, stop:1 #764ba2);\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 15px;\n"
"    margin-top: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #5568d3, stop:1 #6a3f8f);\n"
"}\n"
"QPushButton:pressed {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"        stop:0 #4a5ac1, stop:1 #5e3680);\n"
"}")
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout_right.addWidget(self.login_btn)
        self.register_btn = QtWidgets.QPushButton(self.right_panel)
        self.register_btn.setMinimumSize(QtCore.QSize(0, 55))
        self.register_btn.setStyleSheet("QPushButton {\n"
"    background-color: #10b981;\n"
"    color: white;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    padding: 15px;\n"
"    margin-top: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #059669;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #047857;\n"
"}")
        self.register_btn.setObjectName("register_btn")
        self.verticalLayout_right.addWidget(self.register_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_right.addItem(spacerItem3)
        self.horizontalLayout_main.addWidget(self.right_panel)

        self.retranslateUi(LoginWindow)
        self.btn_close.clicked.connect(LoginWindow.close) # type: ignore
        self.register_btn.clicked.connect(LoginWindow.show_register_dialog) # type: ignore
        self.login_btn.clicked.connect(LoginWindow.login) # type: ignore
        self.refresh_btn.clicked.connect(LoginWindow.refresh_captcha) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "玉米病害检测系统 - 登录"))
        self.title.setText(_translate("LoginWindow", "玉米病害检测系统"))
        self.logo_label.setText(_translate("LoginWindow", "🌽"))
        self.subtitle.setText(_translate("LoginWindow", "玉米病害检测 • 智能识别"))
        self.description.setText(_translate("LoginWindow", "基于深度学习的玉米病害检测系统\n"
"实时识别玉米病害"))
        self.btn_close.setText(_translate("LoginWindow", "×"))
        self.login_title.setText(_translate("LoginWindow", "手势识别登录"))
        self.label_username.setText(_translate("LoginWindow", "用户名"))
        self.icon_username.setText(_translate("LoginWindow", "👤"))
        self.username_input.setPlaceholderText(_translate("LoginWindow", "请输入用户名"))
        self.label_password.setText(_translate("LoginWindow", "密码"))
        self.icon_password.setText(_translate("LoginWindow", "🔒"))
        self.password_input.setPlaceholderText(_translate("LoginWindow", "请输入密码"))
        self.label_captcha.setText(_translate("LoginWindow", "验证码"))
        self.icon_captcha.setText(_translate("LoginWindow", "📧"))
        self.captcha_input.setPlaceholderText(_translate("LoginWindow", "请输入验证码"))
        self.captcha_display.setText(_translate("LoginWindow", "846E"))
        self.login_btn.setText(_translate("LoginWindow", "进入手势识别系统"))
        self.register_btn.setText(_translate("LoginWindow", "注册账号"))
