# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1441, 873)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.collapse_widget2 = QtWidgets.QWidget(self.centralwidget)
        self.collapse_widget2.setMinimumSize(QtCore.QSize(72, 0))
        self.collapse_widget2.setMaximumSize(QtCore.QSize(72, 16777215))
        self.collapse_widget2.setStyleSheet("")
        self.collapse_widget2.setObjectName("collapse_widget2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.collapse_widget2)
        self.verticalLayout_10.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout_10.setSpacing(15)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.titleLayout_2 = QtWidgets.QHBoxLayout()
        self.titleLayout_2.setSpacing(0)
        self.titleLayout_2.setObjectName("titleLayout_2")
        self.toggle_btn_2 = QtWidgets.QPushButton(self.collapse_widget2)
        self.toggle_btn_2.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.toggle_btn_2.setFont(font)
        self.toggle_btn_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggle_btn_2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #4d8f3a, stop:0.5 #8bcf5a, stop:1 #4d8f3a);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 16px;\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #8bcf5a, stop:0.5 #4d8f3a, stop:1 #8bcf5a);\n"
"}")
        self.toggle_btn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggle_btn_2.setIcon(icon)
        self.toggle_btn_2.setIconSize(QtCore.QSize(16, 16))
        self.toggle_btn_2.setCheckable(False)
        self.toggle_btn_2.setAutoRepeat(True)
        self.toggle_btn_2.setObjectName("toggle_btn_2")
        self.titleLayout_2.addWidget(self.toggle_btn_2)
        self.verticalLayout_10.addLayout(self.titleLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_10.addItem(spacerItem)
        self.btnUser2 = QtWidgets.QPushButton(self.collapse_widget2)
        self.btnUser2.setMinimumSize(QtCore.QSize(50, 50))
        self.btnUser2.setMaximumSize(QtCore.QSize(50, 50))
        self.btnUser2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnUser2.setStyleSheet("QPushButton {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(102, 126, 234, 0.9), \n"
"                               stop:0.5 rgba(118, 75, 162, 0.9), \n"
"                               stop:1 rgba(102, 126, 234, 0.9));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: center;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #667eea;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(118, 75, 162, 0.9), \n"
"                               stop:0.5 rgba(102, 126, 234, 0.9), \n"
"                               stop:1 rgba(118, 75, 162, 0.9));\n"
"}")
        self.btnUser2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icon/user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUser2.setIcon(icon1)
        self.btnUser2.setIconSize(QtCore.QSize(40, 40))
        self.btnUser2.setObjectName("btnUser2")
        self.verticalLayout_10.addWidget(self.btnUser2)
        self.btnImage_2 = QtWidgets.QPushButton(self.collapse_widget2)
        self.btnImage_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btnImage_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btnImage_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnImage_2.setStyleSheet("QPushButton {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(105, 164, 73, 0.92), \n"
"                               stop:0.5 rgba(49, 107, 54, 0.92), \n"
"                               stop:1 rgba(105, 164, 73, 0.92));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: center;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #f093fb;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(245, 87, 108, 0.9), \n"
"                               stop:0.5 rgba(240, 147, 251, 0.9), \n"
"                               stop:1 rgba(245, 87, 108, 0.9));\n"
"}")
        self.btnImage_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icon/image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnImage_2.setIcon(icon2)
        self.btnImage_2.setIconSize(QtCore.QSize(40, 40))
        self.btnImage_2.setObjectName("btnImage_2")
        self.verticalLayout_10.addWidget(self.btnImage_2)
        self.btnVideo_2 = QtWidgets.QPushButton(self.collapse_widget2)
        self.btnVideo_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btnVideo_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btnVideo_2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(62, 147, 74, 0.92), \n"
"                               stop:0.5 rgba(134, 187, 83, 0.92), \n"
"                               stop:1 rgba(62, 147, 74, 0.92));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: center;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #4facfe;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(0, 242, 254, 0.9), \n"
"                               stop:0.5 rgba(79, 172, 254, 0.9), \n"
"                               stop:1 rgba(0, 242, 254, 0.9));\n"
"}")
        self.btnVideo_2.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icon/video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVideo_2.setIcon(icon3)
        self.btnVideo_2.setIconSize(QtCore.QSize(40, 40))
        self.btnVideo_2.setObjectName("btnVideo_2")
        self.verticalLayout_10.addWidget(self.btnVideo_2)
        self.btnFolder_2 = QtWidgets.QPushButton(self.collapse_widget2)
        self.btnFolder_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btnFolder_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btnFolder_2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(172, 190, 104, 0.92), \n"
"                               stop:0.5 rgba(111, 150, 74, 0.92), \n"
"                               stop:1 rgba(172, 190, 104, 0.92));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: center;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #ffd89b;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(255, 154, 86, 0.9), \n"
"                               stop:0.5 rgba(255, 216, 155, 0.9), \n"
"                               stop:1 rgba(255, 154, 86, 0.9));\n"
"}")
        self.btnFolder_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icon/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFolder_2.setIcon(icon4)
        self.btnFolder_2.setIconSize(QtCore.QSize(40, 40))
        self.btnFolder_2.setObjectName("btnFolder_2")
        self.verticalLayout_10.addWidget(self.btnFolder_2)
        self.drawer_buttons_2 = QtWidgets.QPushButton(self.collapse_widget2)
        self.drawer_buttons_2.setMinimumSize(QtCore.QSize(50, 50))
        self.drawer_buttons_2.setMaximumSize(QtCore.QSize(50, 50))
        self.drawer_buttons_2.setStyleSheet("QPushButton {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(126, 183, 95, 0.92), \n"
"                               stop:0.5 rgba(201, 217, 138, 0.92), \n"
"                               stop:1 rgba(126, 183, 95, 0.92));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: center;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #a8edea;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(254, 214, 227, 0.9), \n"
"                               stop:0.5 rgba(168, 237, 234, 0.9), \n"
"                               stop:1 rgba(254, 214, 227, 0.9));\n"
"}")
        self.drawer_buttons_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icon/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drawer_buttons_2.setIcon(icon5)
        self.drawer_buttons_2.setIconSize(QtCore.QSize(40, 40))
        self.drawer_buttons_2.setObjectName("drawer_buttons_2")
        self.verticalLayout_10.addWidget(self.drawer_buttons_2)
        self.btnModel_2 = QtWidgets.QPushButton(self.collapse_widget2)
        self.btnModel_2.setMinimumSize(QtCore.QSize(50, 50))
        self.btnModel_2.setMaximumSize(QtCore.QSize(50, 50))
        self.btnModel_2.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(71, 134, 66, 0.92), \n"
"                               stop:0.5 rgba(184, 199, 94, 0.92), \n"
"                               stop:1 rgba(71, 134, 66, 0.92));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: center;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #fa709a;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(254, 225, 64, 0.9), \n"
"                               stop:0.5 rgba(250, 112, 154, 0.9), \n"
"                               stop:1 rgba(254, 225, 64, 0.9));\n"
"}")
        self.btnModel_2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icon/robot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnModel_2.setIcon(icon6)
        self.btnModel_2.setIconSize(QtCore.QSize(40, 40))
        self.btnModel_2.setObjectName("btnModel_2")
        self.verticalLayout_10.addWidget(self.btnModel_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 400, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.horizontalLayout.addWidget(self.collapse_widget2)
        self.collapse_widget = QtWidgets.QWidget(self.centralwidget)
        self.collapse_widget.setEnabled(True)
        self.collapse_widget.setMinimumSize(QtCore.QSize(250, 0))
        self.collapse_widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.collapse_widget.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(22, 33, 62, 0.95), \n"
"                               stop:1 rgba(15, 52, 96, 0.95));\n"
"    border-radius: 18px; \n"
"")
        self.collapse_widget.setObjectName("collapse_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.collapse_widget)
        self.verticalLayout.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLayout = QtWidgets.QHBoxLayout()
        self.titleLayout.setObjectName("titleLayout")
        self.title_label = QtWidgets.QLabel(self.collapse_widget)
        self.title_label.setStyleSheet("    font-size: 28px; \n"
"    font-weight: 800; \n"
"    color: #4facfe;\n"
"    text-shadow: 0 0 20px rgba(126, 183, 95, 0.55);")
        self.title_label.setObjectName("title_label")
        self.titleLayout.addWidget(self.title_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.titleLayout.addItem(spacerItem2)
        self.toggle_btn = QtWidgets.QPushButton(self.collapse_widget)
        self.toggle_btn.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.toggle_btn.setFont(font)
        self.toggle_btn.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #4facfe, stop:0.5 #00f2fe, stop:1 #4facfe);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 16px;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #00f2fe, stop:0.5 #4facfe, stop:1 #00f2fe);\n"
"}")
        self.toggle_btn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icon/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggle_btn.setIcon(icon7)
        self.toggle_btn.setIconSize(QtCore.QSize(16, 16))
        self.toggle_btn.setCheckable(False)
        self.toggle_btn.setDefault(False)
        self.toggle_btn.setFlat(False)
        self.toggle_btn.setObjectName("toggle_btn")
        self.titleLayout.addWidget(self.toggle_btn)
        self.verticalLayout.addLayout(self.titleLayout)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem3)
        self.btnUser = QtWidgets.QPushButton(self.collapse_widget)
        self.btnUser.setMinimumSize(QtCore.QSize(0, 50))
        self.btnUser.setStyleSheet("QPushButton {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(102, 126, 234, 0.9), \n"
"                               stop:0.5 rgba(118, 75, 162, 0.9), \n"
"                               stop:1 rgba(102, 126, 234, 0.9));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #667eea;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(118, 75, 162, 0.9), \n"
"                               stop:0.5 rgba(102, 126, 234, 0.9), \n"
"                               stop:1 rgba(118, 75, 162, 0.9));\n"
"}\n"
"QPushButton[iconMode=\"true\"] {\n"
"    padding: 12px 5px;\n"
"    text-align: center;\n"
"    min-width: 60px;\n"
"    max-width: 60px;\n"
"}\n"
"QPushButton[iconMode=\"true\"]:hover::after {\n"
"    content: attr(tooltip);\n"
"    position: absolute;\n"
"    left: 70px;\n"
"    top: 50%;\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    color: white;\n"
"    padding: 5px 10px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"    white-space: nowrap;\n"
"    z-index: 1000;\n"
"}")
        self.btnUser.setIcon(icon1)
        self.btnUser.setIconSize(QtCore.QSize(20, 20))
        self.btnUser.setObjectName("btnUser")
        self.verticalLayout.addWidget(self.btnUser)
        self.btnImage = QtWidgets.QPushButton(self.collapse_widget)
        self.btnImage.setMinimumSize(QtCore.QSize(0, 50))
        self.btnImage.setStyleSheet("QPushButton {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(240, 147, 251, 0.9), \n"
"                               stop:0.5 rgba(245, 87, 108, 0.9), \n"
"                               stop:1 rgba(240, 147, 251, 0.9));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #f093fb;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(245, 87, 108, 0.9), \n"
"                               stop:0.5 rgba(240, 147, 251, 0.9), \n"
"                               stop:1 rgba(245, 87, 108, 0.9));\n"
"}\n"
"QPushButton[iconMode=\"true\"] {\n"
"    padding: 12px 5px;\n"
"    text-align: center;\n"
"    min-width: 60px;\n"
"    max-width: 60px;\n"
"}\n"
"QPushButton[iconMode=\"true\"]:hover::after {\n"
"    content: attr(tooltip);\n"
"    position: absolute;\n"
"    left: 70px;\n"
"    top: 50%;\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    color: white;\n"
"    padding: 5px 10px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"    white-space: nowrap;\n"
"    z-index: 1000;\n"
"}")
        self.btnImage.setIcon(icon2)
        self.btnImage.setIconSize(QtCore.QSize(20, 20))
        self.btnImage.setObjectName("btnImage")
        self.verticalLayout.addWidget(self.btnImage)
        self.btnVideo = QtWidgets.QPushButton(self.collapse_widget)
        self.btnVideo.setMinimumSize(QtCore.QSize(0, 50))
        self.btnVideo.setStyleSheet("QPushButton {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(79, 172, 254, 0.9), \n"
"                               stop:0.5 rgba(0, 242, 254, 0.9), \n"
"                               stop:1 rgba(79, 172, 254, 0.9));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #4facfe;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(0, 242, 254, 0.9), \n"
"                               stop:0.5 rgba(79, 172, 254, 0.9), \n"
"                               stop:1 rgba(0, 242, 254, 0.9));\n"
"}\n"
"QPushButton[iconMode=\"true\"] {\n"
"    padding: 12px 5px;\n"
"    text-align: center;\n"
"    min-width: 60px;\n"
"    max-width: 60px;\n"
"}\n"
"QPushButton[iconMode=\"true\"]:hover::after {\n"
"    content: attr(tooltip);\n"
"    position: absolute;\n"
"    left: 70px;\n"
"    top: 50%;\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    color: white;\n"
"    padding: 5px 10px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"    white-space: nowrap;\n"
"    z-index: 1000;\n"
"}")
        self.btnVideo.setIcon(icon3)
        self.btnVideo.setIconSize(QtCore.QSize(20, 20))
        self.btnVideo.setObjectName("btnVideo")
        self.verticalLayout.addWidget(self.btnVideo)
        self.btnFolder = QtWidgets.QPushButton(self.collapse_widget)
        self.btnFolder.setMinimumSize(QtCore.QSize(0, 50))
        self.btnFolder.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(255, 216, 155, 0.9), \n"
"                               stop:0.5 rgba(255, 154, 86, 0.9), \n"
"                               stop:1 rgba(255, 216, 155, 0.9));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #ffd89b;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(255, 154, 86, 0.9), \n"
"                               stop:0.5 rgba(255, 216, 155, 0.9), \n"
"                               stop:1 rgba(255, 154, 86, 0.9));\n"
"}\n"
"QPushButton[iconMode=\"true\"] {\n"
"    padding: 12px 5px;\n"
"    text-align: center;\n"
"    min-width: 60px;\n"
"    max-width: 60px;\n"
"}\n"
"QPushButton[iconMode=\"true\"]:hover::after {\n"
"    content: attr(tooltip);\n"
"    position: absolute;\n"
"    left: 70px;\n"
"    top: 50%;\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    color: white;\n"
"    padding: 5px 10px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"    white-space: nowrap;\n"
"    z-index: 1000;\n"
"}")
        self.btnFolder.setIcon(icon4)
        self.btnFolder.setIconSize(QtCore.QSize(20, 20))
        self.btnFolder.setObjectName("btnFolder")
        self.verticalLayout.addWidget(self.btnFolder)
        self.drawer_buttons = QtWidgets.QPushButton(self.collapse_widget)
        self.drawer_buttons.setMinimumSize(QtCore.QSize(0, 50))
        self.drawer_buttons.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(168, 237, 234, 0.9), \n"
"                               stop:0.5 rgba(254, 214, 227, 0.9), \n"
"                               stop:1 rgba(168, 237, 234, 0.9));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #a8edea;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(254, 214, 227, 0.9), \n"
"                               stop:0.5 rgba(168, 237, 234, 0.9), \n"
"                               stop:1 rgba(254, 214, 227, 0.9));\n"
"}\n"
"QPushButton[iconMode=\"true\"] {\n"
"    padding: 12px 5px;\n"
"    text-align: center;\n"
"    min-width: 60px;\n"
"    max-width: 60px;\n"
"}\n"
"QPushButton[iconMode=\"true\"]:hover::after {\n"
"    content: attr(tooltip);\n"
"    position: absolute;\n"
"    left: 70px;\n"
"    top: 50%;\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    color: white;\n"
"    padding: 5px 10px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"    white-space: nowrap;\n"
"    z-index: 1000;\n"
"}")
        self.drawer_buttons.setIcon(icon5)
        self.drawer_buttons.setIconSize(QtCore.QSize(20, 20))
        self.drawer_buttons.setObjectName("drawer_buttons")
        self.verticalLayout.addWidget(self.drawer_buttons)
        self.btnModel = QtWidgets.QPushButton(self.collapse_widget)
        self.btnModel.setMinimumSize(QtCore.QSize(0, 50))
        self.btnModel.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(250, 112, 154, 0.9), \n"
"                               stop:0.5 rgba(254, 225, 64, 0.9), \n"
"                               stop:1 rgba(250, 112, 154, 0.9));\n"
"    color: white;\n"
"    border: none;\n"
"    text-align: left;\n"
"    padding: 14px 18px;\n"
"    border-left: 4px solid #fa709a;\n"
"    border-radius: 12px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"   background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 rgba(254, 225, 64, 0.9), \n"
"                               stop:0.5 rgba(250, 112, 154, 0.9), \n"
"                               stop:1 rgba(254, 225, 64, 0.9));\n"
"}\n"
"QPushButton[iconMode=\"true\"] {\n"
"    padding: 12px 5px;\n"
"    text-align: center;\n"
"    min-width: 60px;\n"
"    max-width: 60px;\n"
"}\n"
"QPushButton[iconMode=\"true\"]:hover::after {\n"
"    content: attr(tooltip);\n"
"    position: absolute;\n"
"    left: 70px;\n"
"    top: 50%;\n"
"    background: rgba(0, 0, 0, 0.8);\n"
"    color: white;\n"
"    padding: 5px 10px;\n"
"    border-radius: 4px;\n"
"    font-size: 12px;\n"
"    white-space: nowrap;\n"
"    z-index: 1000;\n"
"}")
        self.btnModel.setIcon(icon6)
        self.btnModel.setIconSize(QtCore.QSize(20, 20))
        self.btnModel.setObjectName("btnModel")
        self.verticalLayout.addWidget(self.btnModel)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.btnImage.raise_()
        self.btnVideo.raise_()
        self.drawer_buttons.raise_()
        self.btnModel.raise_()
        self.btnFolder.raise_()
        self.btnUser.raise_()
        self.horizontalLayout.addWidget(self.collapse_widget)
        self.centerWidget = QtWidgets.QWidget(self.centralwidget)
        self.centerWidget.setStyleSheet("background-image: url(images/rice_bg.png);\n"
                               "background-repeat: no-repeat;\n"
                               "background-position: center;\n"
                               "background-color: rgba(227, 241, 220, 0.92);\n"
                               "border: 1px solid rgba(82, 124, 61, 0.35);\n"
                               "border-radius: 18px; \n"
                               "")
        self.centerWidget.setObjectName("centerWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centerWidget)
        self.verticalLayout_2.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.topControlLayout = QtWidgets.QHBoxLayout()
        self.topControlLayout.setObjectName("topControlLayout")
        self.confWidget = QtWidgets.QWidget(self.centerWidget)
        self.confWidget.setMinimumSize(QtCore.QSize(0, 42))
        self.confWidget.setMaximumSize(QtCore.QSize(16777215, 42))
        self.confWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.confWidget.setObjectName("confWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.confWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.conf_label = QtWidgets.QLabel(self.confWidget)
        self.conf_label.setStyleSheet("font-size: 14px; \n"
"background-color: rgba(255, 255, 255, 0);\n"
"    font-weight: 600; \n"
"    color: #4facfe;")
        self.conf_label.setObjectName("conf_label")
        self.verticalLayout_4.addWidget(self.conf_label)
        self.conf_slider = QtWidgets.QSlider(self.confWidget)
        self.conf_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #1a2332, stop:0.5 #2d3e5f, stop:1 #1a2332);\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(118, 166, 82, 0.28);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #4facfe, stop:0.5 #00f2fe, stop:1 #4facfe);\n"
"    width: 26px;\n"
"    height: 26px;\n"
"    margin: -9px 0;\n"
"    border-radius: 13px;\n"
"    border: 3px solid #0f3460;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #00f2fe, stop:0.5 #4facfe, stop:1 #00f2fe);\n"
"}")
        self.conf_slider.setMinimum(0)
        self.conf_slider.setMaximum(100)
        self.conf_slider.setProperty("value", 50)
        self.conf_slider.setOrientation(QtCore.Qt.Horizontal)
        self.conf_slider.setObjectName("conf_slider")
        self.verticalLayout_4.addWidget(self.conf_slider)
        self.topControlLayout.addWidget(self.confWidget)
        spacerItem5 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.topControlLayout.addItem(spacerItem5)
        self.iouWidget = QtWidgets.QWidget(self.centerWidget)
        self.iouWidget.setMinimumSize(QtCore.QSize(0, 42))
        self.iouWidget.setMaximumSize(QtCore.QSize(16777215, 42))
        self.iouWidget.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.iouWidget.setObjectName("iouWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.iouWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.iou_label = QtWidgets.QLabel(self.iouWidget)
        self.iou_label.setStyleSheet("font-size: 14px; \n"
"    font-weight: 600; \n"
"    color: #4facfe;")
        self.iou_label.setObjectName("iou_label")
        self.verticalLayout_5.addWidget(self.iou_label)
        self.iou_slider = QtWidgets.QSlider(self.iouWidget)
        self.iou_slider.setStyleSheet("QSlider::groove:horizontal {\n"
"    height: 10px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #1a2332, stop:0.5 #2d3e5f, stop:1 #1a2332);\n"
"    border-radius: 5px;\n"
"    border: 1px solid rgba(79, 172, 254, 0.2);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #4facfe, stop:0.5 #00f2fe, stop:1 #4facfe);\n"
"    width: 26px;\n"
"    height: 26px;\n"
"    margin: -9px 0;\n"
"    border-radius: 13px;\n"
"    border: 3px solid #0f3460;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #00f2fe, stop:0.5 #4facfe, stop:1 #00f2fe);\n"
"}")
        self.iou_slider.setMinimum(0)
        self.iou_slider.setMaximum(100)
        self.iou_slider.setProperty("value", 50)
        self.iou_slider.setOrientation(QtCore.Qt.Horizontal)
        self.iou_slider.setObjectName("iou_slider")
        self.verticalLayout_5.addWidget(self.iou_slider)
        self.topControlLayout.addWidget(self.iouWidget)
        self.verticalLayout_2.addLayout(self.topControlLayout)
        self.statusLayout = QtWidgets.QHBoxLayout()
        self.statusLayout.setObjectName("statusLayout")
        self.time_label = QtWidgets.QLabel(self.centerWidget)
        self.time_label.setMinimumSize(QtCore.QSize(0, 33))
        self.time_label.setMaximumSize(QtCore.QSize(16777215, 33))
        self.time_label.setStyleSheet("font-size: 14px; \n"
"    color: #b0b8c0; \n"
"    font-weight: 500;\n"
"    padding: 6px 12px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 rgba(118, 166, 82, 0.16), \n"
"                               stop:1 rgba(0, 242, 254, 0.15));\n"
"    border: 1px solid rgba(118, 166, 82, 0.34);\n"
"    border-radius: 8px;")
        self.time_label.setObjectName("time_label")
        self.statusLayout.addWidget(self.time_label)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.statusLayout.addItem(spacerItem6)
        self.count_label = QtWidgets.QLabel(self.centerWidget)
        self.count_label.setMinimumSize(QtCore.QSize(0, 33))
        self.count_label.setMaximumSize(QtCore.QSize(16777215, 33))
        self.count_label.setStyleSheet("font-size: 14px; \n"
"    color: #b0b8c0;\n"
"    font-weight: 500;\n"
"    padding: 6px 12px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 rgba(168, 237, 234, 0.15), \n"
"                               stop:1 rgba(254, 214, 227, 0.15));\n"
"    border: 1px solid rgba(168, 237, 234, 0.3);\n"
"    border-radius: 8px;")
        self.count_label.setObjectName("count_label")
        self.statusLayout.addWidget(self.count_label)
        self.verticalLayout_2.addLayout(self.statusLayout)
        self.image_label = QtWidgets.QLabel(self.centerWidget)
        self.image_label.setMinimumSize(QtCore.QSize(419, 100))
        self.image_label.setAutoFillBackground(False)
        self.image_label.setStyleSheet("QLabel {\n"
                               "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                               "                               stop:0 rgba(24, 51, 31, 0.78), \n"
                               "                               stop:1 rgba(79, 123, 68, 0.70));\n"
                               "    border: 2px solid rgba(102, 150, 72, 0.45);\n"
                               "    border-radius: 12px;\n"
                               "    font-size: 16px;\n"
                               "    font-weight: bold;\n"
                               "    color: rgb(255, 255, 255);\n"
                               "}")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.verticalLayout_2.addWidget(self.image_label)
        self.image_bg = QtWebEngineWidgets.QWebEngineView(self.centerWidget)
        self.image_bg.setMinimumSize(QtCore.QSize(419, 100))
        self.image_bg.setAutoFillBackground(False)
        self.image_bg.setStyleSheet("QLabel {\n"
                               "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                               "                               stop:0 rgba(24, 51, 31, 0.78), \n"
                               "                               stop:1 rgba(79, 123, 68, 0.70));\n"
                               "    border: 2px solid rgba(102, 150, 72, 0.45);\n"
                               "    border-radius: 12px;\n"
                               "    color: rgb(255, 255, 255);\n"
                               "}")
        self.image_bg.setObjectName("image_bg")
        self.verticalLayout_2.addWidget(self.image_bg)
        self.table = QtWidgets.QTableWidget(self.centerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(0, 0))
        self.table.setMaximumSize(QtCore.QSize(16777215, 200))
        self.table.setStyleSheet("QTableWidget {\n"
"    border: 1px solid rgba(118, 166, 82, 0.40);\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(15, 20, 45, 0.9), \n"
"                               stop:1 rgba(22, 33, 62, 0.9));\n"
"    gridline-color: rgba(112, 158, 78, 0.20);\n"
"    selection-background-color: rgba(111, 159, 79, 0.30);\n"
"    selection-color: #eff9e8;\n"
"    color: #b0b8c0;\n"
"\n"
"    border-radius: 0px; \n"
"\n"
"}\n"
"\n"
"QHeaderView{\n"
" border-radius: 0px; \n"
"}\n"
"QHeaderView::section {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(118, 166, 82, 0.32), \n"
"                               stop:1 rgba(0, 242, 254, 0.3));\n"
"    color: #eef7ea;\n"
"    padding: 10px;\n"
"    border: none;\n"
"    border-bottom: 2px solid rgba(118, 166, 82, 0.52);\n"
"    font-weight: 600;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"    border-bottom: 1px solid rgba(118, 166, 82, 0.14);\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background: rgba(118, 166, 82, 0.26);\n"
"    color: #00f0ff;\n"
"}")
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.SolidLine)
        self.table.setWordWrap(True)
        self.table.setCornerButtonEnabled(True)
        self.table.setRowCount(5)
        self.table.setColumnCount(5)
        self.table.setObjectName("table")
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.table)
        self.horizontalLayout.addWidget(self.centerWidget)
        self.rightWidget = QtWidgets.QWidget(self.centralwidget)
        self.rightWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.rightWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.rightWidget.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
                               "                               stop:0 rgba(28, 57, 33, 0.86), \n"
                               "                               stop:1 rgba(75, 115, 64, 0.80));\n"
                               "    border-radius: 18px; \n"
                               "")
        self.rightWidget.setObjectName("rightWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.rightWidget)
        self.verticalLayout_3.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logoLayout = QtWidgets.QHBoxLayout()
        self.logoLayout.setObjectName("logoLayout")
        self.logoLabel = QtWidgets.QLabel(self.rightWidget)
        self.logoLabel.setMinimumSize(QtCore.QSize(100, 100))
        self.logoLabel.setMaximumSize(QtCore.QSize(100, 100))
        self.logoLabel.setStyleSheet("QLabel {\n"
"    \n"
"background: white;\n"
"    border-radius: 50px;\n"
"    color: white;\n"
"    font-size: 22px;\n"
"    font-weight: bold;\n"
"}")
        self.logoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.logoLabel.setObjectName("logoLabel")
        self.logoLayout.addWidget(self.logoLabel)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.logoLayout.addItem(spacerItem7)
        self.logoText = QtWidgets.QLabel(self.rightWidget)
        self.logoText.setMaximumSize(QtCore.QSize(16777215, 40))
        self.logoText.setStyleSheet("QLabel {\n"
                               "    font-size: 18px;\n"
                               "    font-weight: 700;\n"
                               "    color: #eef7ea;\n"
                               "    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
                               "                               stop:0 #355e3b, stop:1 #56814f);\n"
                               "    border-radius: 8px;\n"
                               "    padding: 6px 12px;\n"
                               "}")
        self.logoText.setObjectName("logoText")
        self.logoLayout.addWidget(self.logoText)
        self.verticalLayout_3.addLayout(self.logoLayout)
        self.statsGroup = QtWidgets.QGroupBox(self.rightWidget)
        self.statsGroup.setEnabled(False)
        self.statsGroup.setMinimumSize(QtCore.QSize(0, 200))
        self.statsGroup.setStyleSheet("QGroupBox {\n"
"    font-weight: 600;\n"
"    border-radius: 12px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(15, 20, 35, 0.7), \n"
"                               stop:1 rgba(22, 33, 62, 0.7));\n"
"    color: #4facfe;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    \n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    bottom:5px;\n"
"    min-height: 25px;\n"
"    padding: 0px 8px;\n"
"    color: #4facfe;\n"
"}")
        self.statsGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.statsGroup.setFlat(False)
        self.statsGroup.setCheckable(False)
        self.statsGroup.setObjectName("statsGroup")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.statsGroup)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.catlistView = QtWidgets.QListView(self.statsGroup)
        self.catlistView.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catlistView.sizePolicy().hasHeightForWidth())
        self.catlistView.setSizePolicy(sizePolicy)
        self.catlistView.setMinimumSize(QtCore.QSize(0, 151))
        self.catlistView.setMaximumSize(QtCore.QSize(16777215, 150))
        self.catlistView.setAutoFillBackground(False)
        self.catlistView.setStyleSheet("QListView {\n"
"   background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #0a0e27, stop:1 #16213e);\n"
"    border: 1px solid rgba(118, 166, 82, 0.28);\n"
"    border-radius: 8px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    color: #c9d1d9;\n"
"}\n"
"\n"
"QListView::item {\n"
"    height: 36px;\n"
"    padding: 0 12px;\n"
"    margin: 2px 0;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QListView::item:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 rgba(103, 149, 72, 0.22), \n"
"                               stop:1 rgba(0, 242, 254, 0.2));\n"
"    color: #4facfe;\n"
"}\n"
"\n"
"QListView::item:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #578c47, stop:1 #a5d06d);\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}")
        self.catlistView.setObjectName("catlistView")
        self.verticalLayout_14.addWidget(self.catlistView)
        self.verticalLayout_3.addWidget(self.statsGroup)
        self.filterGroup = QtWidgets.QGroupBox(self.rightWidget)
        self.filterGroup.setStyleSheet("QGroupBox {\n"
"    font-weight: 600;\n"
"    border-radius: 12px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(15, 20, 35, 0.7), \n"
"                               stop:1 rgba(22, 33, 62, 0.7));\n"
"    color: #4facfe;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 8px;\n"
"    color: #4facfe;\n"
"    bottom:5px;\n"
"    min-height: 25px;\n"
"}")
        self.filterGroup.setObjectName("filterGroup")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.filterGroup)
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.filter_combo = QtWidgets.QComboBox(self.filterGroup)
        self.filter_combo.setMinimumSize(QtCore.QSize(0, 38))
        self.filter_combo.setStyleSheet("QComboBox {\n"
"    border: 1px solid rgba(79, 172, 254, 0.3);\n"
"    border-radius: 8px;\n"
"    padding: 8px 12px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #0a0e27, stop:1 #16213e);\n"
"    font-size: 15px;\n"
"    color: #c9d1d9;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #4facfe;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 30px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: none;\n"
"    border-left: 5px solid transparent;\n"
"    border-right: 5px solid transparent;\n"
"    border-top: 5px solid #4facfe;\n"
"}\n"
"/* 下拉列表容器 */\n"
"QComboBox QAbstractItemView {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 #16213e, stop:1 #0f3460);\n"
"    border: 2px solid rgba(118, 166, 82, 0.48);\n"
"    border-radius: 8px;\n"
"    selection-background-color: rgba(118, 166, 82, 0.40);\n"
"    selection-color: white;\n"
"    color: #e8f1ff;\n"
"    padding: 5px;\n"
"    outline: none;\n"
"}\n"
"\n"
"/* 下拉列表项 */\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 35px;\n"
"    padding-left: 15px;\n"
"    border-radius: 5px;\n"
"    color: rgb(255, 255, 255);\n"
"    background: transparent;\n"
"}\n"
"\n"
"/* 下拉列表项悬停 */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background: rgba(79, 172, 254, 0.3);\n"
"    color: #00f2fe;\n"
"}\n"
"\n"
"/* 下拉列表项选中 */\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #4facfe, stop:1 #00f2fe);\n"
"    color: white;\n"
"    font-weight: 600;\n"
"}")
        self.filter_combo.setObjectName("filter_combo")
        self.filter_combo.addItem("")
        self.verticalLayout_6.addWidget(self.filter_combo)
        self.verticalLayout_3.addWidget(self.filterGroup)
        self.classGroup = QtWidgets.QGroupBox(self.rightWidget)
        self.classGroup.setStyleSheet("QGroupBox {\n"
"    font-weight: 600;\n"
"    border-radius: 12px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(15, 20, 35, 0.7), \n"
"                               stop:1 rgba(22, 33, 62, 0.7));\n"
"    color: #4facfe;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 8px;\n"
"    color: #4facfe;\n"
"    bottom:5px;\n"
"    min-height: 25px;\n"
"}")
        self.classGroup.setObjectName("classGroup")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.classGroup)
        self.verticalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.category_value = QtWidgets.QPushButton(self.classGroup)
        self.category_value.setMinimumSize(QtCore.QSize(0, 40))
        self.category_value.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #fa709a, stop:1 #fee140);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    font-size: 16px;\n"
"    font-weight: 600;\n"
"    padding: 8px 16px;\n"
"}\n"
"QPushButton:hover {\n"
"}")
        self.category_value.setObjectName("category_value")
        self.verticalLayout_7.addWidget(self.category_value)
        self.verticalLayout_3.addWidget(self.classGroup)
        self.confGroup = QtWidgets.QGroupBox(self.rightWidget)
        self.confGroup.setStyleSheet("QGroupBox {\n"
"    font-weight: 600;\n"
"    border-radius: 12px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(15, 20, 35, 0.7), \n"
"                               stop:1 rgba(22, 33, 62, 0.7));\n"
"    color: #4facfe;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 8px;\n"
"    color: #4facfe;\n"
"    bottom:5px;\n"
"    min-height: 25px;\n"
"}")
        self.confGroup.setObjectName("confGroup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.confGroup)
        self.verticalLayout_8.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.confidence_value = QtWidgets.QLabel(self.confGroup)
        self.confidence_value.setMinimumSize(QtCore.QSize(0, 40))
        self.confidence_value.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #21262d, stop:1 #30363d);\n"
"    border: 2px solid #4facfe;\n"
"    border-radius: 10px;\n"
"    font-size: 20px;\n"
"    font-weight: 700;\n"
"    color: #4facfe;\n"
"}")
        self.confidence_value.setAlignment(QtCore.Qt.AlignCenter)
        self.confidence_value.setObjectName("confidence_value")
        self.verticalLayout_8.addWidget(self.confidence_value)
        self.verticalLayout_3.addWidget(self.confGroup)
        self.posGroup = QtWidgets.QGroupBox(self.rightWidget)
        self.posGroup.setStyleSheet("QGroupBox {\n"
"    font-weight: 600;\n"
"    border-radius: 12px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(15, 20, 35, 0.7), \n"
"                               stop:1 rgba(22, 33, 62, 0.7));\n"
"    color: #4facfe;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    left: 15px;\n"
"    padding: 0 8px;\n"
"    color: #4facfe;\n"
"    bottom:5px;\n"
"    min-height: 25px;\n"
"}")
        self.posGroup.setObjectName("posGroup")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.posGroup)
        self.verticalLayout_9.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_9.setSpacing(5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.posGrid = QtWidgets.QGridLayout()
        self.posGrid.setSpacing(8)
        self.posGrid.setObjectName("posGrid")
        self.label_x_text = QtWidgets.QLabel(self.posGroup)
        self.label_x_text.setStyleSheet("color: #c9d1d9; font-weight: 600;\n"
"text-align: center;\n"
"qproperty-alignment: \'AlignCenter\';")
        self.label_x_text.setObjectName("label_x_text")
        self.posGrid.addWidget(self.label_x_text, 0, 0, 1, 1)
        self.xmin_value = QtWidgets.QLabel(self.posGroup)
        self.xmin_value.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #21262d, stop:1 #2a3441);\n"
"    border: 1px solid rgba(79, 172, 254, 0.4);\n"
"    border-radius: 6px;\n"
"    padding: 4px 6px;\n"
"    color: #4facfe;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    min-width: 35px;\n"
"}")
        self.xmin_value.setAlignment(QtCore.Qt.AlignCenter)
        self.xmin_value.setObjectName("xmin_value")
        self.posGrid.addWidget(self.xmin_value, 0, 1, 1, 1)
        self.label_y_text = QtWidgets.QLabel(self.posGroup)
        self.label_y_text.setStyleSheet("color: #c9d1d9; font-weight: 600;\n"
"text-align: center;\n"
"qproperty-alignment: \'AlignCenter\';")
        self.label_y_text.setObjectName("label_y_text")
        self.posGrid.addWidget(self.label_y_text, 0, 2, 1, 1)
        self.ymin_value = QtWidgets.QLabel(self.posGroup)
        self.ymin_value.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #21262d, stop:1 #2a3441);\n"
"    border: 1px solid rgba(79, 172, 254, 0.4);\n"
"    border-radius: 6px;\n"
"    padding: 4px 6px;\n"
"    color: #4facfe;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    min-width: 35px;\n"
"}")
        self.ymin_value.setAlignment(QtCore.Qt.AlignCenter)
        self.ymin_value.setObjectName("ymin_value")
        self.posGrid.addWidget(self.ymin_value, 0, 3, 1, 1)
        self.label_z1_text = QtWidgets.QLabel(self.posGroup)
        self.label_z1_text.setStyleSheet("color: #c9d1d9; font-weight: 600;\n"
"text-align: center;\n"
"qproperty-alignment: \'AlignCenter\';")
        self.label_z1_text.setObjectName("label_z1_text")
        self.posGrid.addWidget(self.label_z1_text, 1, 0, 1, 1)
        self.xmax_value = QtWidgets.QLabel(self.posGroup)
        self.xmax_value.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #21262d, stop:1 #2a3441);\n"
"    border: 1px solid rgba(79, 172, 254, 0.4);\n"
"    border-radius: 6px;\n"
"    padding: 4px 6px;\n"
"    color: #4facfe;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    min-width: 35px;\n"
"}")
        self.xmax_value.setAlignment(QtCore.Qt.AlignCenter)
        self.xmax_value.setObjectName("xmax_value")
        self.posGrid.addWidget(self.xmax_value, 1, 1, 1, 1)
        self.label_z2_text = QtWidgets.QLabel(self.posGroup)
        self.label_z2_text.setStyleSheet("color: #c9d1d9; font-weight: 600;\n"
"text-align: center;\n"
"qproperty-alignment: \'AlignCenter\';")
        self.label_z2_text.setObjectName("label_z2_text")
        self.posGrid.addWidget(self.label_z2_text, 1, 2, 1, 1)
        self.ymax_value = QtWidgets.QLabel(self.posGroup)
        self.ymax_value.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                               stop:0 #21262d, stop:1 #2a3441);\n"
"    border: 1px solid rgba(79, 172, 254, 0.4);\n"
"    border-radius: 6px;\n"
"    padding: 4px 6px;\n"
"    color: #4facfe;\n"
"    font-weight: 600;\n"
"    font-size: 14px;\n"
"    min-width: 35px;\n"
"}")
        self.ymax_value.setAlignment(QtCore.Qt.AlignCenter)
        self.ymax_value.setObjectName("ymax_value")
        self.posGrid.addWidget(self.ymax_value, 1, 3, 1, 1)
        self.verticalLayout_9.addLayout(self.posGrid)
        self.verticalLayout_3.addWidget(self.posGroup)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.horizontalLayout.addWidget(self.rightWidget)
        self.userWidget = QtWidgets.QWidget(self.centralwidget)
        self.userWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.userWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.userWidget.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(22, 33, 62, 0.95), \n"
"                               stop:1 rgba(15, 52, 96, 0.95));\n"
"    border-radius: 18px; \n"
"")
        self.userWidget.setObjectName("userWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.userWidget)
        self.verticalLayout_11.setContentsMargins(15, 20, 15, 20)
        self.verticalLayout_11.setSpacing(15)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.avatarWidget = QtWidgets.QWidget(self.userWidget)
        self.avatarWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.avatarWidget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.avatarWidget.setStyleSheet("QWidget{\n"
"font-weight: 600;\n"
"    border-radius: 12px;\n"
"    margin-top: 10px;\n"
"    padding-top: 15px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(15, 20, 35, 0.7), \n"
"                               stop:1 rgba(22, 33, 62, 0.7));\n"
"    color: #4facfe;\n"
"}")
        self.avatarWidget.setObjectName("avatarWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.avatarWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.avatar_label = QtWidgets.QLabel(self.avatarWidget)
        self.avatar_label.setMinimumSize(QtCore.QSize(180, 180))
        self.avatar_label.setMaximumSize(QtCore.QSize(180, 180))
        self.avatar_label.setStyleSheet("QLabel {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(10, 14, 39, 0.8), \n"
"                               stop:1 rgba(22, 33, 62, 0.8));\n"
"    qproperty-alignment: \'AlignHCenter | AlignVCenter\';\n"
"    border-radius: 0px; \n"
"}")
        self.avatar_label.setText("")
        self.avatar_label.setObjectName("avatar_label")
        self.gridLayout.addWidget(self.avatar_label, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.avatarWidget)
        self.widget = QtWidgets.QWidget(self.userWidget)
        self.widget.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                               stop:0 rgba(10, 14, 39, 0.8), \n"
"                               stop:1 rgba(22, 33, 62, 0.8));\n"
"    border-radius: 12px;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.username_title = QtWidgets.QLabel(self.widget)
        self.username_title.setMinimumSize(QtCore.QSize(0, 30))
        self.username_title.setMaximumSize(QtCore.QSize(75, 30))
        self.username_title.setStyleSheet("font-size: 12px; \n"
"    color: #ffffff; \n"
"    font-weight: 500;\n"
"    padding: 6px 12px;")
        self.username_title.setObjectName("username_title")
        self.horizontalLayout_2.addWidget(self.username_title)
        self.username_value = QtWidgets.QLabel(self.widget)
        self.username_value.setMinimumSize(QtCore.QSize(0, 30))
        self.username_value.setMaximumSize(QtCore.QSize(16777215, 30))
        self.username_value.setStyleSheet("font-size: 14px; \n"
"    color: #ffffff; \n"
"color: rgb(221, 221, 221);\n"
"    font-weight: 500;\n"
"    padding: 6px 12px;\n"
"text-align: center;\n"
"qproperty-alignment: \'AlignCenter\';")
        self.username_value.setObjectName("username_value")
        self.horizontalLayout_2.addWidget(self.username_value)
        self.verticalLayout_11.addWidget(self.widget)
        self.modify_btn = QtWidgets.QPushButton(self.userWidget)
        self.modify_btn.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #667eea, stop:1 #764ba2);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 12px 20px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #764ba2, stop:1 #667eea);\n"
"}")
        self.modify_btn.setObjectName("modify_btn")
        self.verticalLayout_11.addWidget(self.modify_btn)
        self.logout_btn = QtWidgets.QPushButton(self.userWidget)
        self.logout_btn.setStyleSheet("QPushButton {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #667eea, stop:1 #764ba2);\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 12px 20px;\n"
"    font-weight: 600;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                               stop:0 #764ba2, stop:1 #667eea);\n"
"}")
        self.logout_btn.setObjectName("logout_btn")
        self.verticalLayout_11.addWidget(self.logout_btn)
        spacerItem9 = QtWidgets.QSpacerItem(20, 361, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.horizontalLayout.addWidget(self.userWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btnImage.clicked.connect(MainWindow.open_image_file) # type: ignore
        self.btnVideo.clicked.connect(MainWindow.open_video_file) # type: ignore
        self.btnFolder.clicked.connect(MainWindow.open_folder) # type: ignore
        self.drawer_buttons.clicked.connect(MainWindow.open_camera) # type: ignore
        self.btnModel.clicked.connect(MainWindow.select_model_file) # type: ignore
        self.conf_slider.valueChanged['int'].connect(MainWindow.confValueChanged) # type: ignore
        self.iou_slider.valueChanged['int'].connect(MainWindow.iouValueChanged) # type: ignore
        self.filter_combo.currentIndexChanged['QString'].connect(MainWindow.on_filter_changed) # type: ignore
        self.toggle_btn.clicked.connect(MainWindow.toggle_collapse) # type: ignore
        self.toggle_btn_2.clicked.connect(MainWindow.toggle_collapse) # type: ignore
        self.btnImage_2.clicked.connect(MainWindow.open_image_file) # type: ignore
        self.btnVideo_2.clicked.connect(MainWindow.open_video_file) # type: ignore
        self.btnFolder_2.clicked.connect(MainWindow.open_folder) # type: ignore
        self.drawer_buttons_2.clicked.connect(MainWindow.open_camera) # type: ignore
        self.btnModel_2.clicked.connect(MainWindow.select_model_file) # type: ignore
        self.btnUser.clicked.connect(MainWindow.show_user_info) # type: ignore
        self.btnUser2.clicked.connect(MainWindow.show_user_info) # type: ignore
        self.modify_btn.clicked.connect(MainWindow.open_modify_user_dialog) # type: ignore
        self.logout_btn.clicked.connect(MainWindow.prompt_logout) # type: ignore
        self.table.itemSelectionChanged.connect(MainWindow.on_detection_selected) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于YOLO的跌倒检测系统"))
        self.title_label.setText(_translate("MainWindow", "跌倒检测"))
        self.btnUser.setText(_translate("MainWindow", "个人中心"))
        self.btnImage.setText(_translate("MainWindow", " 图片选择"))
        self.btnVideo.setText(_translate("MainWindow", "视频选择"))
        self.btnFolder.setText(_translate("MainWindow", "文件夹选择"))
        self.drawer_buttons.setText(_translate("MainWindow", "摄像头"))
        self.btnModel.setText(_translate("MainWindow", "模型选择"))
        self.conf_label.setText(_translate("MainWindow", "置信度 (Conf): 0.5"))
        self.iou_label.setText(_translate("MainWindow", "交并比 (IoU): 0.5"))
        self.time_label.setText(_translate("MainWindow", "⏱ 检测耗时: 0.00s"))
        self.count_label.setText(_translate("MainWindow", "🎯 检测目标: 0个"))
        self.image_label.setText(_translate("MainWindow", "dafasd"))
        self.table.setSortingEnabled(False)
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "序号"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文件路径"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "类别"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "置信度"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "坐标位置"))
        self.logoLabel.setText(_translate("MainWindow", "Y"))
        self.logoText.setText(_translate("MainWindow", "YOLO检测系统"))
        self.statsGroup.setTitle(_translate("MainWindow", "📊 类别统计"))
        self.filterGroup.setTitle(_translate("MainWindow", "🔍 类别过滤:"))
        self.filter_combo.setItemText(0, _translate("MainWindow", "显示所有类别"))
        self.classGroup.setTitle(_translate("MainWindow", "🔲 检测类别:"))
        self.category_value.setText(_translate("MainWindow", "未选择"))
        self.confGroup.setTitle(_translate("MainWindow", "📊 置信度:"))
        self.confidence_value.setText(_translate("MainWindow", "0.00"))
        self.posGroup.setTitle(_translate("MainWindow", "📍 坐标位置:"))
        self.label_x_text.setText(_translate("MainWindow", "<html><head/><body><p>X</p></body></html>"))
        self.xmin_value.setText(_translate("MainWindow", "0"))
        self.label_y_text.setText(_translate("MainWindow", "<html><head/><body><p>Y</p></body></html>"))
        self.ymin_value.setText(_translate("MainWindow", "0"))
        self.label_z1_text.setText(_translate("MainWindow", "<html><head/><body><p>X</p></body></html>"))
        self.xmax_value.setText(_translate("MainWindow", "0"))
        self.label_z2_text.setText(_translate("MainWindow", "Y"))
        self.ymax_value.setText(_translate("MainWindow", "0"))
        self.username_title.setText(_translate("MainWindow", "用户名:"))
        self.username_value.setText(_translate("MainWindow", "未知用户"))
        self.modify_btn.setText(_translate("MainWindow", "修改用户信息"))
        self.logout_btn.setText(_translate("MainWindow", "注销用户"))
from PyQt5 import QtWebEngineWidgets
